### ISSUE TITLE
excludeFields() seems to actually perform an "includeOnlyThis"

### ISSUE THREAD

**Issue by centic9** [nambach/ExcelUtil#12]
Current condition in ColumnTemplate#excludeFields is `removeIf(m -> !fields.contains(m.getField())` which means it removes all fields that are not in the list of removed fields. This is the wrong way around as far as I see.

**Comment by nambach** [comment]
Thank you, I will check that.

**Comment by nambach** [comment]
Fixed at bf683b4385b316b5042477e1f9f8c0ff63b6f671 (See release [2.3.2-SNAPSHOT](https://github.com/nambach/ExcelUtil/releases/tag/2.3.2-SNAPSHOT))

**Comment by nambach** [comment]
[Update] The official release for this issue is [v2.3.2](https://github.com/nambach/ExcelUtil/releases/tag/v2.3.2). Please have a check.
