### ISSUE TITLE
Please add documentation for extending / customizing the Validation framework

### ISSUE THREAD

**Issue by fvanwesterop** [nambach/ExcelUtil#15]
I noticed the WIKI has a link https://github.com/nambach/ExcelUtil/wiki/Reading-Validation
But that page does not exist. I'm trying to create a custom validator but can't get it to work. Adding that page might help.
(In particular I'm trying to create a validator that either allows null or empty cells or a valid integer.)

**Comment by nambach** [comment]
Hi Frank, thanks for trying this tool. I will update the wiki as soon as possible.

**Comment by nambach** [comment]
Hi @fvanwesterop, I have updated the wiki for reading validation https://github.com/nambach/ExcelUtil/wiki/Reading-Validation. 
Please remember to update the library's version to `2.3.2` first. Any problem regarding validation, please open another issue.
