### ISSUE TITLE
SequentialWriter does not reset cell pointer when creating new sheets

### ISSUE THREAD

**Issue by prof-thies-pfeiffer** [nambach/ExcelUtil#22]
I use the SequentialWriter in one of my applications. After upgrading to ExelUtil 2.4.0 and POI 5.1 the behavior of the SequentialWriter has changed. After creating a new sheet, the cursor now sticks in the position it had in the previous sheet. New content will then typically be added in the next row beyond the last row of the content added last to the previous sheet. Thus, if you iteratively create new sheets and add content, you end up with an increased number of empty rows leading the actual content. In previous versions, content in new sheets was always added starting from the top row. This seems to be a bug.

Example code (entires contains a HashMap of filled data templates):

SequentialWriter writer = new SequentialWriter();
for( String sheet : entries.keySet() ) {
            writer.createNewSheet(sheet);
            writer.writeData(REPORT_TEMPLATE, entries.get(sheet));
}
InputStream stream = writer.exportToFile();
FileUtil.writeToDisk(filename, stream, true);

**Comment by nambach** [comment]
Hi @prof-thies-pfeiffer, I have fixed this issue in version 2.4.1. Please update in your code.

**Comment by nambach** [comment]
Just in case you didn't know, there are many guides in the section ["Wiki"](https://github.com/nambach/ExcelUtil/wiki) that you may find useful. Please take a look.

**Comment by prof-thies-pfeiffer** [comment]
Hi @nambach, thank you for the impressively quick reaction. I can confirm that the problem is fixed in 2.4.1.
Thank you for the efforts you are putting in this!
